#!/bin/bash
echo "Generating js/supabase-config.js from environment variables..."

# Create the config file using environment variables from Vercel
cat <<EOF > js/supabase-config.js
/* Supabase Backend Integration Configuration */
/* Auto-generated by Vercel during build */

window.SUPABASE_URL = "$SUPABASE_URL";
window.SUPABASE_ANON_KEY = "$SUPABASE_ANON_KEY";

console.log("✅ Supabase config loaded via Vercel build script.");
EOF

echo "Build complete!"
